{{- if .Values.secureDocker }}

{{- $ca := genCA "docker:dind ca" 825 }}
{{- $servercert := genSignedCert "docker:dind server" nil (list (include "dind.fullname" .) "docker" "localhost") 825 $ca }}
{{- $clientcert := genSignedCert "docker:dind client" nil nil 825 $ca }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dind.fullname" . }}-cert-server
  namespace: {{ $.Release.Namespace | quote }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $servercert.Cert | b64enc | quote }}
  tls.key: {{ $servercert.Key | b64enc | quote }}
  ca.crt: {{ $ca.Cert | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dind.fullname" . }}-cert-client
  namespace: {{ $.Release.Namespace | quote }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $clientcert.Cert | b64enc | quote }}
  tls.key: {{ $clientcert.Key | b64enc | quote }}
  ca.crt: {{ $ca.Cert | b64enc | quote }}

{{- end }}
