{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dind.fullname" . }}
  labels:
    {{- include "dind.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.service.port }}
    - port: {{ .Values.service.port }}
    {{- else }}
    - port: {{ include "dind.dockerPort" . }}
    {{- end }}
    {{- if .Values.service.targetPort }}
      targetPort: {{ .Values.service.targetPort }}
    {{- else }}
      targetPort: {{ include "dind.dockerPort" . }}
    {{- end }}
      protocol: TCP
      name: docker
  selector:
    {{- include "dind.selectorLabels" . | nindent 4 }}
{{- end }}
