name: Main branch workflow

on:
  push:
    branches:
      - main

jobs:

  release:

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "Peter W"
          git config user.email "31324861+peterwwillis@users.noreply.github.com"

      ### Begin releasing
      - name: Install Helm
        uses: azure/setup-helm@v3
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      ### Begin updating index
      - name: Update index.yaml
        run: |
            owner="$(cut -d '/' -f 1 <<< "$GITHUB_REPOSITORY")"
            repo="$(cut -d '/' -f 2 <<< "$GITHUB_REPOSITORY")"
            version="v1.5.0"
            curl -sSLo /tmp/cr.tar.gz "https://github.com/helm/chart-releaser/releases/download/$version/chart-releaser_${version#v}_linux_amd64.tar.gz"
            tar -xzf /tmp/cr.tar.gz -C "/usr/local/bin"
            rm -f /tmp/cr.tar.gz
            /usr/local/bin/cr index -o "$owner" -r "$repo" --push
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      ### Begin publishing HTML
      - name: Generate HTML from Markdown
        uses: ldeluigi/markdown-docs@latest
        with:
          src: ./charts/docker-in-docker
          dst: .

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: .
          keep_history: "true"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

