name: Main branch workflow

on:
  push:
    branches:
      - main

  workflow_dispatch:


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  publish-html:
    permissions:
      contents: write
    uses: ./.github/workflows/publish-html.yml

  update-index:
    permissions:
      contents: write
    uses: ./.github/workflows/update-index.yml

  release:
    permissions:
      contents: write
    uses: ./.github/workflows/release.yml
  
