name: Publish HTML docs for the chart

on:
  workflow_call:

jobs:

  publish-html:

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "Peter W"
          git config user.email "31324861+peterwwillis@users.noreply.github.com"

      - name: Generate HTML from Markdown
        uses: ldeluigi/markdown-docs@latest
        with:
          src: ./charts/docker-in-docker
          dst: public

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
